language: python

# Supported Python versions
python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4


env:
  - DJANGO_SETTINGS_MODULE="authors.settings"
# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
 - psql -c "create database ah_theunsullied;" -U postgres

# Run tests
script:
  - python manage.py migrate
  - pytest --cov-report term-missing --cov=authors/apps -p no:warnings
  - coverage report

# Generate coverage report
after_success:
  - coveralls
