language: python

# Supported Python versions
python:
  - "3.6"

services:
  - postgresql

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coveralls
before_script:
 - psql -c 'create database ah_unsullied_test' -U postgres

# Run tests
script:
  - python manage.py makemigrations 
  - python manage.py migrate 
  - coverage run --source=authors/ manage.py test 
  - coverage report

# Generate coverage report
after_success:
  - coveralls

