# Generated by Django 2.1.4 on 2019-01-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rating'),
        ('articles', '0002_auto_20190131_0938'),
    ]

    operations = [
    ]
