# Generated by Django 2.1.4 on 2019-02-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_taglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkarticlemodel',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='bookmarkarticlemodel',
            old_name='user',
            new_name='user_id',
        ),
    ]
