# Generated by Django 2.1.4 on 2019-02-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_merge_20190131_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_Child',
        ),
        migrations.RemoveField(
            model_name='historicalcomments',
            name='is_Child',
        ),
    ]
