# Generated by Django 2.1.4 on 2019-02-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190201_1325'),
        ('articles', '0005_auto_20190201_1229'),
    ]

    operations = [
    ]
