# Generated by Django 2.1.4 on 2019-02-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_merge_20190203_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tagList',
            new_name='tag_list',
        ),
    ]
