# Generated by Django 2.1.4 on 2019-02-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190204_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.TextField(default='null'),
        ),
    ]
